
function StateSuggestions() {
this.states = 
[
"ACCESSKENYA GROUP LTD.","ACHAR BROTHERS ENTERPRISES.","ACUITY VENTURES LTD.","ADOLA LABORATORIES.","ADSOLUTE HI-TECH LTD.","AFRICA COLLECT TEXTILES.","AGUS GENERAL CONSTRUCTION.","ALIBHAI SHARIFF.","ANTARC LTD.","APDK","ARROW RUBBER STAMP CO.LTD.","ASTERISK LIMITED.","AUTO EXPRESS LTD.","BESTMEC AUTO SERVICES.","BESTWAYS STATIONERS","BIODEAL LABORATORIES","BIOHAZARD WASTE SOUTIONS E.A LTD.","BIOMED EA MEDICAL SUPPLIES LTD.","BIOQUEST KENYA LTD.","BIOSCAN DIAGNOSTICS","BIOTOP SUPPLIERS","BLUE EDGE SOLUTIONS.","BOB MORGAN SYSTEMS LIMITED.","BOC KENYA LTD.","BRACKENHURST HOTEL AND CONFERENCES.","BRAND IT BY TERS SOLUTIONS.","BRITAM GENERAL INSURANCE COMPANY (K) LTD.","BRITISH AMERICAN INSURANCE COMPANY (K) LTD.","BRITISH PHARMACEUTICALS LTD.","CANON RADIOLOGICAL SERVICES.","CHANDARIA INDUSTRIES LIMITED","CHARLSITY INVESTMENTS.","CHEM LABS LTD.","CHEMOQUIP LTD.","CISTEIN PHARMACEUTICALS LTD","CITY COUNCIL OF NAIROBI","CLIMACENTO GREEN TECH LTD.","CMC MOTORS GROUP LTD.","COLOUR INTERNATIONAL","COMMERCIAL BANK OF AFRICA.","COMMSCOPE TECHNOLOGIES","CRESCENT SERVICE STATION LTD.","CROWN HEALTHCARE.","CYROPACK LTD.","DAVIS & SHIRTLIFF LTD.","DEEPAFRICA LTD.","DIVERSEY EASTERN & CENTRAL AFRICA LTD.","EMBROIDME INTERNATIONAL KENYA LTD.","EMMA NELIMA KHAEMBA (BIOSTATISTICIAN&CONSULTANT IN RESEARCH AND STATISTICS)","EPISON TECH.","EXCEL MEDICAL SUPPLIES","FARMERS CHOICE LTD","FAST CHOICE LTD.","FEDERATION OF KENYA EMPLOYERS.","FURNITURE ELEGANCE LTD.","GALAXY PHARMACEUTICALS","GAME DISCOUNT WORLD (K) LTD.","GELPHA LTD.","GEMINI FIVE ENTERPRISES","GEMINIA INSURANCE CO.LTD.","GREEN SHIELD ASSOCIATES.","HISTOCHEM DIAGNOSTICS","HOLLEY COTEC CO.(EA) LTD.","HOTPOINT APPLIANCES LTD.","HUQAS","ICEA LION GENERAL INSURANCE COMPANY LTD.","ICEA LION LIFE ASSURANCE COMPANY LTD.","IMS GURU LIMITED.","INNOVATIVE TECHNOLOGIES LTD.","INZAMELLEN ENTERPRISES.","ITAL PRODUCTS LTD.","JANST INTERNATIONAL HEALTHCARE","JB MOTORS LTD.","JESTECH LIMITED.","JOCARL ELECTRICAL & HARDWARE.","KAMP-PRISK-MPAKE.","KARIOBANGI WOMEN PROMOTION TRAINING INSTITUTE.","KARISHMA HEALTHCARE SOLUTIONS.","KASA PACK 4PRISING YOUTH SELF HELP GROUP.","KENPOLY MANUFACTURERS LTD","KENYA COMMUNITY DEVELOPMENT FOUNDATION.","KENYA MEDICAL SUPPLIES AUTHORITY.","KENYA POWER AND LIGHTING COMPANY.","KENYA REVENUE AUTHORITY.","KENYA TENTS LIMITED.","KIBISHI HARDWARE AND ELECTRICALS LTD.","KRISHNA CHEMISTS LTD.","LAB REAGENTS AND CONSUMABLES.","LABOREX KENYA LTD.","LEADSOFT TECHNOLOGIES.","LORDS HEALTHCARE LTD","MAGABIT TECHNOLOGIES LTD","MARKEN SURGICAL SUPPLIES.","MARLIES GENERAL SUPPLIERS","MARSHA EAST AFRICA LAB SUPPLIES.","MAXIM PHARMACEUTICALS LTD.","MEDEX EAST AFRICA LTD.","MEDIPHARM EAST AFRICA LTD.","MEDISEL (K) LTD.","MEDISYST LIMITED.","MEDS","MEGABIT TECHNOLOGIES LTD.","MGK ASSOCIATES.","MICHIMEDIA LIMITED.","MIDMED EAST AFRICA LTD.","MILMES LTD.","MINGLES SUPPLY LIMITED.","MOIBEN HOLDINGS LTD.","MP SHAH HOSPITAL.","MR.GABRIELE BEACCO.","MUREX INTERNATIONAL LTD.","MURNA CONSULTANTS.","NAIROBI CITY WATER AND SEWERAGE COMPANY LTD.","NAIVAS LIMITED","NATIONAL ENVIRONMENT MANAGEMENT AUTHORITY.","NATIONAL PHARMACY LTD","NATIVE MEDIA TECHNOLOGIES.","NEEMA STAFF WELFARE ASSOCIATION.","NEOLITE TECHNICAL SERVICES.","NIMROD AFRICA LTD.","NIMUTELCOMM ENGINEERING SYSTEMS LTD.","NJIMIA PHARMACEUTICALS LTD.","NJORONI COMPUTER SERVICES","OCTOPUS CONSULTANCY LIMITED.","OFFICE MART LTD.","OLEANDER SOLUTIONS LIMITED.","OMAERA PHARMACEUTICALS LTD.","ON THE GRIND COFFEE BAR AND KITCHEN.","OPEN DATA LIMITED.","ORAD MOTORSPORTS.","OTTO TAILORS.","PACIFIC DIAGNOSTICS LTD.","PACIS INSURANCE COMPANY LTD.","PAN PHARMACEUTICALS LTD.","PANKIM OFFICE SUPPLIES LTD.","PARMA MEDICAL EQUIPMENT.","PETROM CONSTRUCTION COMPANY LTD.","PHARMA LIFE SCIENCE LTD.","PHARMAKEN LTD.","PHILS AUTO GARAGE LTD.","PHYSICAL THERAPY SERVICES LTD.","PLENSER LIMITED.","POSTURE CONSULTING LTD.","PROSUP ENTERPRISES","PULSE HEALTHCARE LTD.","QUANTUM SCIENTIFIC LIMITED.","RADIANCE PHARMACEUTICALS LTD.","RANCO REFRIGERATION&AIR CONDITIONING.","RANGECHEM PHARMACEUTICALS LTD.","RESOLUTE EXPERTS INVESTMENT LTD.","RIELLO POWER SOLUTIONS LTD.","ROHIL BUILDERS LTD.","ROTARY CLUB OF ONGATA RONGAI.","SAFARICOM LTD.","SAFETY TECH LTD.","SAI PHARMACEUTICALS","SAILEN SUPPLIERS.","SAM-TECH DIAGNOSTICS LTD.","SAMEER AGRICULTURE & LIVESTOCK (KENYA) LTD.","SD SARUK DIGITAL","SEROPHARM EAST AFRICA LTD","SHAMCO INDUSTRIES LTD.","SOWETO TUSAIDIANE VISION WOMEN GROUP","STEWAR LIMITED.","STRATHMORE BUSINESS SCHOOL.","SURGEMED SUPPLIES LTD.","SURGIPHARM LIMITED","SYNTHECON KENYA LTD.","TARGET TECH SUPPLIES LTD.","TECH-SUPPORT DIAGNOSTICS.","TELKOM KENYA LTD.","TERRYS BEST CUTS BUTCHERY.","THE KENYA POWER AND LIGHTING COMPANY LTD.","THE KENYAN ALLIANCE COMPANY LTD.","THE MEDICAL PRACTITIONERS AND DENTISTS BOARD.","TIS DIRECT LTD.","TOWFIQ (K) LTD.","TRANSBIZ ENTERPRISES.","TRANSWIDE PHARMACEUTICALS LTD.","TUOREN COMPANY LIMITED.","UDCHEM DIAGNOSTICS","UNI INDUSTRIES EAST AFRICA LIMITED.","UNIVERSAL CORPORATION LTD.","VERIMED ENTERPRISES LTD.","WARRICK DIAGNOSTICS SERVICES.","WATER RESOURCES MANAGEMENT AUTHORITY.","WAUMINI SACCO SOCIETY LTD.","WAYNTA BUILDERS (K) LTD.","WIZ CONSULTING LTD.","ZAWADI HEALTHCARE LTD.","ZURIPLUS LIMITED."];
}

/**
 * Request suggestions for the given autosuggest control. 
 * @scope protected
 * @param oAutoSuggestControl The autosuggest control to provide suggestions for.
 */
StateSuggestions.prototype.requestSuggestions = function (oAutoSuggestControl /*:AutoSuggestControl*/,
                                                          bTypeAhead /*:boolean*/) {
    var aSuggestions = [];
    var sTextboxValue = oAutoSuggestControl.textbox.value;
    
 	var loopLength = 0;

    if (sTextboxValue.length > 0){
    
	var sTextboxValue = sTextboxValue.toUpperCase();

        //search for matching states
        for (var i=0; i < this.states.length; i++) 
		{ 
            if (this.states[i].indexOf(sTextboxValue) >= 0) 
			{
                loopLength = loopLength + 1;
				if (loopLength <= 15) //TO REDUCE THE SUGGESTIONS DROP DOWN LIST
				{
					aSuggestions.push(this.states[i]);
				}
            } 
        }
    }

    //provide suggestions to the control
    oAutoSuggestControl.autosuggest(aSuggestions, bTypeAhead);
};