
function StateSuggestions1() {
this.states = 
[
"AFB/VA ||AFB STAINING","AIC/VA|| HBA1C","ALB/VA|| ALBUMIN","ALP/VA|| ALKALINE PHOSPHATASE(ADULT MALE)","ANC/VA|| ANC PROFILE(B.GROUP HB VDRL & URINALYSIS)","ARV/VA|| ADENO/ROTA VIRUS","ASOT/VA|| ASOT TEST","BAT/VA|| BRUCELLOSIS TEST","BGL/VA|| RANDOM BLOOD SUGAR RBS","BGR/VA|| BLOOD GROUPING","BHCG/VA|| BETA HCG","BILD/VA|| DIRECT BILIRUBIN","BILT/VA|| TOTAL BILIRUBIN (AT BIRTH)","BS/VA|| BS FOR MPS","CAL/VA|| CALCIUM","CHL/VA|| CHLORIDES","CHOL/VA|| TOTAL CHOLESTEROL","CRT/VA|| CREATININE(MALE)","ESR/VA|| ERYTHROCYTE SEDIMENTATION RATE ESR","FBS/VA|| FASTING BLOOD SUGAR FBS","FHGM|| FULL HAEMOGRAM(MALE ADULT)","FT3/VA|| T3","FT4/VA|| T4","GGT|| GAMMA GT","HB/VA|| HAEMOGLOBIN LEVELS HB","HDL/VA|| HIGH DENSITY LIPOPROTEIN","HISTLVA|| TISSUE BIOPSY FOR HISTOLOGY LARGE","HISTSVA|| TISSUE BIOPSY FOR HISTOLOGY SMALL","HIVR/VA|| HIV TESTING AND COUNSELLING (VCT)","HPAB/VA|| HELICOBACTER PYLORI ANTIBODIES","HPAG/VA|| HELICOBACTER PYLORI ANTIGEN","HVSCS/VA|| HVS/URETHRAL C/S","LAB001|| FULL HAEMOGRAM(FEMALE ADULT)","LAB0012|| CD4 COUNTS","LAB002|| FULL HAEMOGRAM(CHILD)","LAB003|| BILIRUBIN TOTAL (ADULTS)","LAB004|| HVS MICROSCOPY AND GRAM STAIN","LAB005|| ICT","LAB005/1|| KOH","LAB008|| PREURAL EFFUSION(ZN STAIN)","LAB009|| PREURAL EFFUSION(CULTURE AND SENSITIVITY)","LAB010|| PREURAL EFFUSION(WETPREP AND GRAM STAIN)","LAB011|| HEPATITIS B ANTIGEN","LAB012|| NEW ITEM","LAB013|| SICKLING TEST","LAB014|| PROGESTERONE","LAB015|| LUTEINIZING HORMONE (LH)","LAB016|| PROLACTIN  (PRL)","LAB017|| BLOOD GROUPING AND CROSSMATCH","LAB018|| HEPATITIS C VIRUS","LAB019|| ALKALINE PHOSPHATASE-MALE ADULT","LAB021|| CRAG TEST","LAB023|| DIRECT COOMBS TEST","LAB024|| CSF ANALYSIS","LAB024/1|| BLOOD CULTURE","LAB025|| CMV","LAB025|| C REACTIVE PROTEIN (LATEX)","LAB026|| ELECTROLYTES","LAB027/1|| CA 125","LAB028|| HISTOLOGY","LAB029|| ALKALINE PHOSPHATASE- FEMALE ADULTS","LAB030|| ALKALINE PHOSPHATASE - CHILDREN UPTO 15 YEARS","LAB031|| ALKALINE PHOSPHATASE (CHILDREN UPTO 17 YEARS)","LAB032|| TOTAL BILIRUBIN (5 DAYS-1 MONTH)","LAB033|| TOTAL BILIRUBIN (1 MONTH - 12 YEARS)","LAB034|| TOTAL BILIRUBIN (ADULTS)","LAB035|| PCR","LAB036|| SALMONELLA STOOL ANTIGEN","LAB037|| TB CULTURE","LAB038|| FLUID ASPIRATE CULTURE & SENSITIVITY","LAB039|| VIRAL LOAD","LAB040|| CSF CULTURE AND SENSITIVITY","LAB041|| C.R.P-QUANTATIVE","LAB042|| ANTI CCP","LAB043|| PSA","LAB044|| POTASSIUM","LAB045|| CSF FM TEST(TB)","LAB046|| CREATININE (FEMALE)","LAB047|| DU TEST","LAB048|| IMMUNOHISTOCHEMISTRY","LAB049|| TESTOSTERONE","LAB050|| B-HCG","LAB051|| CORTISOL TEST","LAB052|| CEA (CARCINOEMBRYONIC ANTIGEN CANCER BLOOD TEST)","LAB053|| FOLLICLE STIMULATING HORMONE","LDL/VA|| LOW DENSITY LIPOPROTEIN","LFT/VA|| LIVER FUNCTION TESTS","LIPID/VA|| LIPID PROFILE","OCC/VA|| FECAL OCCULT BLOOD","OGTT/VA|| OGTT(ORAL GLUCOSE TOLERANCE TEST)","PAPR/VA|| PAP SMEAR REPORTING","PBF/VA|| PERIPHERAL BLOOD FILM","PDT/VA|| PREGNANCY DIAGNOSTIC TEST","PROT/VA|| SERUM PROTEINS","PSAQUAL/VA|| PROSTATIC SURFACE ANTIGEN SCREENING","PSAQUAN/VA|| TPSA QUANTITATIVE","PUSCS/VA|| PUS CULTURE AND SENSITIVITY","RF/VA|| RHEUMATOID FACTOR","SA/VA|| SEMEN ANALYSIS","SGOT/VA|| SGOT (AST)","SGPT/VA|| SGPT (ALT)","SOD/VA|| SODIUM","STCS/VA|| STOOL CULTURE /SENSITIVITY","STLOC/VA|| STOOL FOR OVA/ CYSTS","TFT/VA|| THYROID FUNCTION TEST TFTS","TPHA/VA|| TPHA","TRY/VA|| TRYGLYCERIDES","TS/VA|| THROAT SWAB C/S","TSH/VA|| TSH","UA/VA|| URINALYSIS","UAC/VA|| URINE M/C:S","UEC/VA|| RENAL FUNCTION TEST U/E:C","UR/VA|| UREA","URA/VA|| URIC ACID","VDRL/VA|| VDRL/KHAN:RPR","WETPRET/VA|| URETHRAL SWAB","WID/VA|| WIDAL TEST"];
}

/**
 * Request suggestions for the given autosuggest control. 
 * @scope protected
 * @param oAutoSuggestControl The autosuggest control to provide suggestions for.
 */
StateSuggestions1.prototype.requestSuggestions = function (AutoSuggestControl1 /*:AutoSuggestControl*/,
                                                          bTypeAhead /*:boolean*/) {
    var aSuggestions = [];
    var sTextboxValue = AutoSuggestControl1.textbox.value;
    //alert (sTextboxValue);
 	var loopLength = 0;

    if (sTextboxValue.length > 0){
    
	var sTextboxValue = sTextboxValue.toUpperCase();

        //search for matching states
        for (var i=0; i < this.states.length; i++) 
		{ 
            if (this.states[i].indexOf(sTextboxValue) >= 0) 
			{
                loopLength = loopLength + 1;
				if (loopLength <= 15) //TO REDUCE THE SUGGESTIONS DROP DOWN LIST
				{
					aSuggestions.push(this.states[i]);
				}
            } 
        }
    }

    //provide suggestions to the control
    AutoSuggestControl1.autosuggest(aSuggestions, bTypeAhead);
};